// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_brew/test/ui/beverages_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_brew/data/model/beverage_detail_result.dart' as _i6;
import 'package:flutter_brew/data/model/beverage_result.dart' as _i4;
import 'package:flutter_brew/data/model/beverage_type.dart' as _i7;
import 'package:flutter_brew/data/model/search_history.dart' as _i9;
import 'package:flutter_brew/data/repository/beverage_repository.dart' as _i2;
import 'package:flutter_brew/data/repository/search_history_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BeverageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeverageRepository extends _i1.Mock
    implements _i2.BeverageRepository {
  @override
  _i3.Future<_i4.BeverageResult> getAllBeverage() => (super.noSuchMethod(
        Invocation.method(
          #getAllBeverage,
          [],
        ),
        returnValue: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #getAllBeverage,
            [],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #getAllBeverage,
            [],
          ),
        )),
      ) as _i3.Future<_i4.BeverageResult>);

  @override
  _i3.Future<_i4.BeverageResult> getHotBeverage() => (super.noSuchMethod(
        Invocation.method(
          #getHotBeverage,
          [],
        ),
        returnValue: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #getHotBeverage,
            [],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #getHotBeverage,
            [],
          ),
        )),
      ) as _i3.Future<_i4.BeverageResult>);

  @override
  _i3.Future<_i6.BeverageDetailResult> getHotBeverageDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHotBeverageDetail,
          [id],
        ),
        returnValue: _i3.Future<_i6.BeverageDetailResult>.value(
            _i5.dummyValue<_i6.BeverageDetailResult>(
          this,
          Invocation.method(
            #getHotBeverageDetail,
            [id],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i6.BeverageDetailResult>.value(
            _i5.dummyValue<_i6.BeverageDetailResult>(
          this,
          Invocation.method(
            #getHotBeverageDetail,
            [id],
          ),
        )),
      ) as _i3.Future<_i6.BeverageDetailResult>);

  @override
  _i3.Future<_i4.BeverageResult> getIcedBeverage() => (super.noSuchMethod(
        Invocation.method(
          #getIcedBeverage,
          [],
        ),
        returnValue: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #getIcedBeverage,
            [],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #getIcedBeverage,
            [],
          ),
        )),
      ) as _i3.Future<_i4.BeverageResult>);

  @override
  _i3.Future<_i6.BeverageDetailResult> getIcedBeverageDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIcedBeverageDetail,
          [id],
        ),
        returnValue: _i3.Future<_i6.BeverageDetailResult>.value(
            _i5.dummyValue<_i6.BeverageDetailResult>(
          this,
          Invocation.method(
            #getIcedBeverageDetail,
            [id],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i6.BeverageDetailResult>.value(
            _i5.dummyValue<_i6.BeverageDetailResult>(
          this,
          Invocation.method(
            #getIcedBeverageDetail,
            [id],
          ),
        )),
      ) as _i3.Future<_i6.BeverageDetailResult>);

  @override
  _i3.Future<_i6.BeverageDetailResult> getBeverageDetail(
    int? id,
    _i7.BeverageType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBeverageDetail,
          [
            id,
            type,
          ],
        ),
        returnValue: _i3.Future<_i6.BeverageDetailResult>.value(
            _i5.dummyValue<_i6.BeverageDetailResult>(
          this,
          Invocation.method(
            #getBeverageDetail,
            [
              id,
              type,
            ],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i6.BeverageDetailResult>.value(
            _i5.dummyValue<_i6.BeverageDetailResult>(
          this,
          Invocation.method(
            #getBeverageDetail,
            [
              id,
              type,
            ],
          ),
        )),
      ) as _i3.Future<_i6.BeverageDetailResult>);

  @override
  _i3.Future<_i4.BeverageResult> findSearchWords(String? words) =>
      (super.noSuchMethod(
        Invocation.method(
          #findSearchWords,
          [words],
        ),
        returnValue: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #findSearchWords,
            [words],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #findSearchWords,
            [words],
          ),
        )),
      ) as _i3.Future<_i4.BeverageResult>);

  @override
  _i3.Future<_i4.BeverageResult> getIsFavoriteTrueBeverages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getIsFavoriteTrueBeverages,
          [],
        ),
        returnValue: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #getIsFavoriteTrueBeverages,
            [],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.BeverageResult>.value(
            _i5.dummyValue<_i4.BeverageResult>(
          this,
          Invocation.method(
            #getIsFavoriteTrueBeverages,
            [],
          ),
        )),
      ) as _i3.Future<_i4.BeverageResult>);

  @override
  _i3.Future<_i6.BeverageDetailResult> updateFavorite(
    int? id,
    _i7.BeverageType? type,
    bool? isFavorite,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFavorite,
          [
            id,
            type,
            isFavorite,
          ],
        ),
        returnValue: _i3.Future<_i6.BeverageDetailResult>.value(
            _i5.dummyValue<_i6.BeverageDetailResult>(
          this,
          Invocation.method(
            #updateFavorite,
            [
              id,
              type,
              isFavorite,
            ],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i6.BeverageDetailResult>.value(
            _i5.dummyValue<_i6.BeverageDetailResult>(
          this,
          Invocation.method(
            #updateFavorite,
            [
              id,
              type,
              isFavorite,
            ],
          ),
        )),
      ) as _i3.Future<_i6.BeverageDetailResult>);
}

/// A class which mocks [SearchHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchHistoryRepository extends _i1.Mock
    implements _i8.SearchHistoryRepository {
  @override
  _i3.Future<List<_i9.SearchHistory>> getSearchHistories(String? words) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistories,
          [words],
        ),
        returnValue:
            _i3.Future<List<_i9.SearchHistory>>.value(<_i9.SearchHistory>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i9.SearchHistory>>.value(<_i9.SearchHistory>[]),
      ) as _i3.Future<List<_i9.SearchHistory>>);

  @override
  _i3.Future<void> saveSearchHistory(String? words) => (super.noSuchMethod(
        Invocation.method(
          #saveSearchHistory,
          [words],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
