name: Check and test the source code
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test --coverage
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage to console
        run: |
          lcov --list coverage/lcov.info --list-full-path --rc lcov_branch_coverage=1
      - name: Generate code coverage html
        run: |
          genhtml coverage/lcov.info --output-directory coverage/html
      - name: Upload coverage to artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Report coverage to GitHub
        uses: k1LoW/octocov-action@v1
